<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FeedCSVRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedCSVRepository extends EntityRepository
{
    public function retrieveNextCsvFeed($source, $locale)
    {
        $query = $this->_em->createQuery(
            "
                SELECT
                  s
                FROM AppBundle\Entity\FeedCSV s
                WHERE s.source = :source
                AND s.flagbatched = 'N'
                AND s.active = 'Y'
                AND s.locale = :locale
            "
        );

        $query->setParameter('locale', $locale);
        $query->setParameter('source', strtoupper($source));
        $query->setMaxResults(1);
        $query->setFirstResult(0);
        $results = $query->getResult();

        return $results[0];

    }

    public function findLogoFromActiveSite()
    {
        $query = $this->_em->createQuery(
            "
                SELECT
                s
                FROM AppBundle:FeedCSV s
                WHERE s.active = 'Y'
            "
        );

        //$query->useQueryCache(true);

        $results = $query->getResult();

        return $results;
    }
    
}
